export const characterDataSchema = {
  name: {
    position: { y: 4.9, x: 4.5 },
    size: { height: 2.6, width: 57 },
    className: "absolute text-sm",
    placeholder: "Nombre...",
    type: "input",
  },
  "experience.1": {
    type: "checkbox",
    position: { y: 5, x: 63.9 },
    size: { width: 1, height: 1.5 },
    appearance: "tick",
  },
  "experience.2": {
    type: "checkbox",
    position: { y: 5, x: 65.3 },
    size: { width: 1, height: 1.5 },
    appearance: "tick",
  },
  "experience.3": {
    type: "checkbox",
    position: { y: 5, x: 66.7 },
    size: { width: 1, height: 1.5 },
    appearance: "tick",
  },
  "experience.4": {
    type: "checkbox",
    position: { y: 5, x: 68 },
    size: { width: 1, height: 1.5 },
    appearance: "tick",
  },
  "experience.5": {
    type: "checkbox",
    position: { y: 5, x: 69.4 },
    size: { width: 1, height: 1.5 },
    appearance: "tick",
  },
  "experience.6": {
    type: "checkbox",
    position: { y: 5, x: 70.8 },
    size: { width: 1, height: 1.5 },
    appearance: "tick",
  },
  "experience.7": {
    type: "checkbox",
    position: { y: 5, x: 72.2 },
    size: { width: 1, height: 1.5 },
    appearance: "tick",
  },
  "experience.8": {
    type: "checkbox",
    position: { y: 5, x: 73.6 },
    size: { width: 1, height: 1.5 },
    appearance: "tick",
  },
  "experience.9": {
    type: "checkbox",
    position: { y: 5, x: 75 },
    size: { width: 1, height: 1.5 },
    appearance: "tick",
  },
  "experience.10": {
    type: "checkbox",
    position: { y: 5, x: 76.4 },
    size: { width: 1, height: 1.5 },
    appearance: "tick",
  },
  "experience.11": {
    type: "checkbox",
    position: { y: 5, x: 77.8 },
    size: { width: 1, height: 1.5 },
    appearance: "tick",
  },
  "experience.12": {
    type: "checkbox",
    position: { y: 5, x: 79.1 },
    size: { width: 1, height: 1.5 },
    appearance: "tick",
  },
  "experience.13": {
    type: "checkbox",
    position: { y: 5, x: 80.5 },
    size: { width: 1, height: 1.5 },
    appearance: "tick",
  },
  "experience.14": {
    type: "checkbox",
    position: { y: 5, x: 81.9 },
    size: { width: 1, height: 1.5 },
    appearance: "tick",
  },
  "experience.15": {
    type: "checkbox",
    position: { y: 5, x: 83.3 },
    size: { width: 1, height: 1.5 },
    appearance: "tick",
  },
  "experience.16": {
    type: "checkbox",
    position: { y: 6.4, x: 63.9 },
    size: { width: 1, height: 1.5 },
    appearance: "tick",
  },
  "experience.17": {
    type: "checkbox",
    position: { y: 6.4, x: 65.3 },
    size: { width: 1, height: 1.5 },
    appearance: "tick",
  },
  "experience.18": {
    type: "checkbox",
    position: { y: 6.4, x: 66.7 },
    size: { width: 1, height: 1.5 },
    appearance: "tick",
  },
  "experience.19": {
    type: "checkbox",
    position: { y: 6.4, x: 68 },
    size: { width: 1, height: 1.5 },
    appearance: "tick",
  },
  "experience.20": {
    type: "checkbox",
    position: { y: 6.4, x: 69.4 },
    size: { width: 1, height: 1.5 },
    appearance: "tick",
  },
  "experience.21": {
    type: "checkbox",
    position: { y: 6.4, x: 70.8 },
    size: { width: 1, height: 1.5 },
    appearance: "tick",
  },
  "experience.22": {
    type: "checkbox",
    position: { y: 6.4, x: 72.2 },
    size: { width: 1, height: 1.5 },
    appearance: "tick",
  },
  "experience.23": {
    type: "checkbox",
    position: { y: 6.4, x: 73.6 },
    size: { width: 1, height: 1.5 },
    appearance: "tick",
  },
  "experience.24": {
    type: "checkbox",
    position: { y: 6.4, x: 75 },
    size: { width: 1, height: 1.5 },
    appearance: "tick",
  },
  "experience.25": {
    type: "checkbox",
    position: { y: 6.4, x: 76.4 },
    size: { width: 1, height: 1.5 },
    appearance: "tick",
  },
  "experience.26": {
    type: "checkbox",
    position: { y: 6.4, x: 77.8 },
    size: { width: 1, height: 1.5 },
    appearance: "tick",
  },
  "experience.27": {
    type: "checkbox",
    position: { y: 6.4, x: 79.1 },
    size: { width: 1, height: 1.5 },
    appearance: "tick",
  },
  "experience.28": {
    type: "checkbox",
    position: { y: 6.4, x: 80.5 },
    size: { width: 1, height: 1.5 },
    appearance: "tick",
  },
  "experience.29": {
    type: "checkbox",
    position: { y: 6.4, x: 81.9 },
    size: { width: 1, height: 1.5 },
    appearance: "tick",
  },
  "experience.30": {
    type: "checkbox",
    position: { y: 6.4, x: 83.3 },
    size: { width: 1, height: 1.5 },
    appearance: "tick",
  },
  edge: {
    position: { y: 9.3, x: 15.2 },
    size: { height: 4.5, width: 13.8 },
    className: "absolute text-lg text-center",
    type: "input",
  },
  heart: {
    position: { y: 9.3, x: 29.2 },
    size: { height: 4.5, width: 13.8 },
    className: "absolute text-lg text-center",
    type: "input",
  },
  iron: {
    position: { y: 9.3, x: 43.2 },
    size: { height: 4.5, width: 13.8 },
    className: "absolute text-lg text-center",
    type: "input",
  },
  shadow: {
    position: { y: 9.3, x: 57.1 },
    size: { height: 4.5, width: 13.8 },
    className: "absolute text-lg text-center",
    type: "input",
  },
  wits: {
    position: { y: 9.3, x: 71.1 },
    size: { height: 4.5, width: 13.8 },
    className: "absolute text-lg text-center",
    type: "input",
  },
  "bonds.1": {
    position: { y: 20 - 0.2, x: 32.2 },
    size: { width: 3 },
    type: "multicheckbox",
  },
  "bonds.2": {
    position: { y: 20 - 0.2, x: 35.8 },
    size: { width: 3 },
    type: "multicheckbox",
  },
  "bonds.3": {
    position: { y: 20 - 0.2, x: 39.4 },
    size: { width: 3 },
    type: "multicheckbox",
  },
  "bonds.4": {
    position: { y: 20 - 0.2, x: 43.1 },
    size: { width: 3 },
    type: "multicheckbox",
  },
  "bonds.5": {
    position: { y: 20 - 0.2, x: 46.7 },
    size: { width: 3 },
    type: "multicheckbox",
  },
  "bonds.6": {
    position: { y: 20 - 0.2, x: 50.3 },
    size: { width: 3 },
    type: "multicheckbox",
  },
  "bonds.7": {
    position: { y: 20 - 0.2, x: 53.9 },
    size: { width: 3 },
    type: "multicheckbox",
  },
  "bonds.8": {
    position: { y: 20 - 0.2, x: 57.6 },
    size: { width: 3 },
    type: "multicheckbox",
  },
  "bonds.9": {
    position: { y: 20 - 0.2, x: 61.2 },
    size: { width: 3 },
    type: "multicheckbox",
  },
  "bonds.10": {
    position: { y: 20 - 0.2, x: 64.8 },
    size: { width: 3 },
    type: "multicheckbox",
  },

  "vows.1.description": {
    position: { y: 26.5, x: 15.5 },
    size: { height: 1.8, width: 69 },
    className: "absolute text-sm",
    type: "input",
  },
  "vows.1.check.1": {
    type: "checkbox",
    position: { y: 28.8, x: 22 },
    size: { width: 1, height: 1.5 },
    appearance: "tick",
  },
  "vows.1.check.2": {
    type: "checkbox",
    position: { y: 28.8, x: 36.7 },
    size: { width: 1, height: 1.5 },
    appearance: "tick",
  },
  "vows.1.check.3": {
    type: "checkbox",
    position: { y: 28.8, x: 49.2 },
    size: { width: 1, height: 1.5 },
    appearance: "tick",
  },
  "vows.1.check.4": {
    type: "checkbox",
    position: { y: 28.8, x: 62.2 },
    size: { width: 1, height: 1.5 },
    appearance: "tick",
  },
  "vows.1.check.5": {
    type: "checkbox",
    position: { y: 28.8, x: 72.7 },
    size: { width: 1, height: 1.5 },
    appearance: "tick",
  },
  "vows.1.multicheck.1": {
    position: { y: 30.7, x: 32.2 },
    size: { width: 3 },
    type: "multicheckbox",
  },
  "vows.1.multicheck.2": {
    position: { y: 30.7, x: 35.8 },
    size: { width: 3 },
    type: "multicheckbox",
  },
  "vows.1.multicheck.3": {
    position: { y: 30.7, x: 39.4 },
    size: { width: 3 },
    type: "multicheckbox",
  },
  "vows.1.multicheck.4": {
    position: { y: 30.7, x: 43.1 },
    size: { width: 3 },
    type: "multicheckbox",
  },
  "vows.1.multicheck.5": {
    position: { y: 30.7, x: 46.7 },
    size: { width: 3 },
    type: "multicheckbox",
  },
  "vows.1.multicheck.6": {
    position: { y: 30.7, x: 50.3 },
    size: { width: 3 },
    type: "multicheckbox",
  },
  "vows.1.multicheck.7": {
    position: { y: 30.7, x: 53.9 },
    size: { width: 3 },
    type: "multicheckbox",
  },
  "vows.1.multicheck.8": {
    position: { y: 30.7, x: 57.6 },
    size: { width: 3 },
    type: "multicheckbox",
  },
  "vows.1.multicheck.9": {
    position: { y: 30.7, x: 61.2 },
    size: { width: 3 },
    type: "multicheckbox",
  },
  "vows.1.multicheck.10": {
    position: { y: 30.7, x: 64.8 },
    size: { width: 3 },
    type: "multicheckbox",
  },
  "vows.2.description": {
    position: { y: 34.6, x: 15.5 },
    size: { height: 1.8, width: 69 },
    className: "absolute text-sm",
    type: "input",
  },

  "vows.2.check.1": {
    type: "checkbox",
    position: { y: 37, x: 22 },
    size: { width: 1, height: 1.5 },
    appearance: "tick",
  },
  "vows.2.check.2": {
    type: "checkbox",
    position: { y: 37, x: 36.7 },
    size: { width: 1, height: 1.5 },
    appearance: "tick",
  },
  "vows.2.check.3": {
    type: "checkbox",
    position: { y: 37, x: 49.2 },
    size: { width: 1, height: 1.5 },
    appearance: "tick",
  },
  "vows.2.check.4": {
    type: "checkbox",
    position: { y: 37, x: 62.2 },
    size: { width: 1, height: 1.5 },
    appearance: "tick",
  },
  "vows.2.check.5": {
    type: "checkbox",
    position: { y: 37, x: 72.7 },
    size: { width: 1, height: 1.5 },
    appearance: "tick",
  },

  "vows.2.multicheck.1": {
    position: { y: 38.8, x: 32.2 },
    size: { width: 3 },
    type: "multicheckbox",
  },
  "vows.2.multicheck.2": {
    position: { y: 38.8, x: 35.8 },
    size: { width: 3 },
    type: "multicheckbox",
  },
  "vows.2.multicheck.3": {
    position: { y: 38.8, x: 39.4 },
    size: { width: 3 },
    type: "multicheckbox",
  },
  "vows.2.multicheck.4": {
    position: { y: 38.8, x: 43.1 },
    size: { width: 3 },
    type: "multicheckbox",
  },
  "vows.2.multicheck.5": {
    position: { y: 38.8, x: 46.7 },
    size: { width: 3 },
    type: "multicheckbox",
  },
  "vows.2.multicheck.6": {
    position: { y: 38.8, x: 50.3 },
    size: { width: 3 },
    type: "multicheckbox",
  },
  "vows.2.multicheck.7": {
    position: { y: 38.8, x: 53.9 },
    size: { width: 3 },
    type: "multicheckbox",
  },
  "vows.2.multicheck.8": {
    position: { y: 38.8, x: 57.6 },
    size: { width: 3 },
    type: "multicheckbox",
  },
  "vows.2.multicheck.9": {
    position: { y: 38.8, x: 61.2 },
    size: { width: 3 },
    type: "multicheckbox",
  },
  "vows.2.multicheck.10": {
    position: { y: 38.8, x: 64.8 },
    size: { width: 3 },
    type: "multicheckbox",
  },

  "vows.3.description": {
    position: { y: 42.7, x: 15.5 },
    size: { height: 1.8, width: 69 },
    className: "absolute text-sm",
    type: "input",
  },

  "vows.3.check.1": {
    type: "checkbox",
    position: { y: 45, x: 22 },
    size: { width: 1, height: 1.5 },
    appearance: "tick",
  },
  "vows.3.check.2": {
    type: "checkbox",
    position: { y: 45, x: 36.7 },
    size: { width: 1, height: 1.5 },
    appearance: "tick",
  },
  "vows.3.check.3": {
    type: "checkbox",
    position: { y: 45, x: 49.2 },
    size: { width: 1, height: 1.5 },
    appearance: "tick",
  },
  "vows.3.check.4": {
    type: "checkbox",
    position: { y: 45, x: 62.2 },
    size: { width: 1, height: 1.5 },
    appearance: "tick",
  },
  "vows.3.check.5": {
    type: "checkbox",
    position: { y: 45, x: 72.7 },
    size: { width: 1, height: 1.5 },
    appearance: "tick",
  },

  "vows.3.multicheck.1": {
    position: { y: 46.9, x: 32.2 },
    size: { width: 3 },
    type: "multicheckbox",
  },
  "vows.3.multicheck.2": {
    position: { y: 46.9, x: 35.8 },
    size: { width: 3 },
    type: "multicheckbox",
  },
  "vows.3.multicheck.3": {
    position: { y: 46.9, x: 39.4 },
    size: { width: 3 },
    type: "multicheckbox",
  },
  "vows.3.multicheck.4": {
    position: { y: 46.9, x: 43.1 },
    size: { width: 3 },
    type: "multicheckbox",
  },
  "vows.3.multicheck.5": {
    position: { y: 46.9, x: 46.7 },
    size: { width: 3 },
    type: "multicheckbox",
  },
  "vows.3.multicheck.6": {
    position: { y: 46.9, x: 50.3 },
    size: { width: 3 },
    type: "multicheckbox",
  },
  "vows.3.multicheck.7": {
    position: { y: 46.9, x: 53.9 },
    size: { width: 3 },
    type: "multicheckbox",
  },
  "vows.3.multicheck.8": {
    position: { y: 46.9, x: 57.6 },
    size: { width: 3 },
    type: "multicheckbox",
  },
  "vows.3.multicheck.9": {
    position: { y: 46.9, x: 61.2 },
    size: { width: 3 },
    type: "multicheckbox",
  },
  "vows.3.multicheck.10": {
    position: { y: 46.9, x: 64.8 },
    size: { width: 3 },
    type: "multicheckbox",
  },

  "vows.4.description": {
    position: { y: 50.800000000000004, x: 15.5 },
    size: { height: 1.8, width: 69 },
    className: "absolute text-sm",
    type: "input",
  },

  "vows.4.check.1": {
    type: "checkbox",
    position: { y: 53.2, x: 22 },
    size: { width: 1, height: 1.5 },
    appearance: "tick",
  },
  "vows.4.check.2": {
    type: "checkbox",
    position: { y: 53.2, x: 36.7 },
    size: { width: 1, height: 1.5 },
    appearance: "tick",
  },
  "vows.4.check.3": {
    type: "checkbox",
    position: { y: 53.2, x: 49.2 },
    size: { width: 1, height: 1.5 },
    appearance: "tick",
  },
  "vows.4.check.4": {
    type: "checkbox",
    position: { y: 53.2, x: 62.2 },
    size: { width: 1, height: 1.5 },
    appearance: "tick",
  },
  "vows.4.check.5": {
    type: "checkbox",
    position: { y: 53.2, x: 72.7 },
    size: { width: 1, height: 1.5 },
    appearance: "tick",
  },

  "vows.4.multicheck.1": {
    position: { y: 55, x: 32.2 },
    size: { width: 3 },
    type: "multicheckbox",
  },
  "vows.4.multicheck.2": {
    position: { y: 55, x: 35.8 },
    size: { width: 3 },
    type: "multicheckbox",
  },
  "vows.4.multicheck.3": {
    position: { y: 55, x: 39.4 },
    size: { width: 3 },
    type: "multicheckbox",
  },
  "vows.4.multicheck.4": {
    position: { y: 55, x: 43.1 },
    size: { width: 3 },
    type: "multicheckbox",
  },
  "vows.4.multicheck.5": {
    position: { y: 55, x: 46.7 },
    size: { width: 3 },
    type: "multicheckbox",
  },
  "vows.4.multicheck.6": {
    position: { y: 55, x: 50.3 },
    size: { width: 3 },
    type: "multicheckbox",
  },
  "vows.4.multicheck.7": {
    position: { y: 55, x: 53.9 },
    size: { width: 3 },
    type: "multicheckbox",
  },
  "vows.4.multicheck.8": {
    position: { y: 55, x: 57.6 },
    size: { width: 3 },
    type: "multicheckbox",
  },
  "vows.4.multicheck.9": {
    position: { y: 55, x: 61.2 },
    size: { width: 3 },
    type: "multicheckbox",
  },
  "vows.4.multicheck.10": {
    position: { y: 55, x: 64.8 },
    size: { width: 3 },
    type: "multicheckbox",
  },

  "vows.5.description": {
    position: { y: 59, x: 15.5 },
    size: { height: 1.8, width: 69 },
    className: "absolute text-sm",
    type: "input",
  },

  "vows.5.check.1": {
    type: "checkbox",
    position: { y: 61.2, x: 22 },
    size: { width: 1, height: 1.5 },
    appearance: "tick",
  },
  "vows.5.check.2": {
    type: "checkbox",
    position: { y: 61.2, x: 36.7 },
    size: { width: 1, height: 1.5 },
    appearance: "tick",
  },
  "vows.5.check.3": {
    type: "checkbox",
    position: { y: 61.2, x: 49.2 },
    size: { width: 1, height: 1.5 },
    appearance: "tick",
  },
  "vows.5.check.4": {
    type: "checkbox",
    position: { y: 61.2, x: 62.2 },
    size: { width: 1, height: 1.5 },
    appearance: "tick",
  },
  "vows.5.check.5": {
    type: "checkbox",
    position: { y: 61.2, x: 72.7 },
    size: { width: 1, height: 1.5 },
    appearance: "tick",
  },

  "vows.5.multicheck.1": {
    position: { y: 63.2, x: 32.2 },
    size: { width: 3 },
    type: "multicheckbox",
  },
  "vows.5.multicheck.2": {
    position: { y: 63.2, x: 35.8 },
    size: { width: 3 },
    type: "multicheckbox",
  },
  "vows.5.multicheck.3": {
    position: { y: 63.2, x: 39.4 },
    size: { width: 3 },
    type: "multicheckbox",
  },
  "vows.5.multicheck.4": {
    position: { y: 63.2, x: 43.1 },
    size: { width: 3 },
    type: "multicheckbox",
  },
  "vows.5.multicheck.5": {
    position: { y: 63.2, x: 46.7 },
    size: { width: 3 },
    type: "multicheckbox",
  },
  "vows.5.multicheck.6": {
    position: { y: 63.2, x: 50.3 },
    size: { width: 3 },
    type: "multicheckbox",
  },
  "vows.5.multicheck.7": {
    position: { y: 63.2, x: 53.9 },
    size: { width: 3 },
    type: "multicheckbox",
  },
  "vows.5.multicheck.8": {
    position: { y: 63.2, x: 57.6 },
    size: { width: 3 },
    type: "multicheckbox",
  },
  "vows.5.multicheck.9": {
    position: { y: 63.2, x: 61.2 },
    size: { width: 3 },
    type: "multicheckbox",
  },
  "vows.5.multicheck.10": {
    position: { y: 63.2, x: 64.8 },
    size: { width: 3 },
    type: "multicheckbox",
  },
  health: {
    position: { y: 11.1, x: 87 },
    size: { width: 8.7, height: 23.6 },
    type: "radiogroup",
    amount: 6,
    className: {
      container: "flex gap-1 flex-col",
      button: "relative h-full grid place-content-center place-items-center",
    },
    appearance: "circle",
  },
  spirit: {
    position: { y: 36.7, x: 87 },
    size: { width: 8.7, height: 23.6 },
    type: "radiogroup",
    amount: 6,
    className: {
      container: "flex gap-1 flex-col",
      button: "relative h-full grid place-content-center place-items-center",
    },
    appearance: "circle",
  },
  supplies: {
    position: { y: 62, x: 87 },
    size: { width: 8.7, height: 23.6 },
    type: "radiogroup",
    amount: 6,
    className: {
      container: "flex gap-1 flex-col",
      button: "relative h-full grid place-content-center place-items-center",
    },
    appearance: "circle",
  },
  momentum: {
    position: { y: 9.2, x: 4.2 },
    size: { width: 8.7, height: 66.8 },
    type: "radiogroup",
    amount: 17,
    className: {
      container: "flex gap-1 flex-col",
      button: "relative h-full grid place-content-center place-items-center",
    },
    appearance: "circle",
  },
  "momentum.max": {
    position: { y: 76.2, x: 4.4 },
    size: { height: 4.7, width: 8.7 },
    className: "absolute text-lg text-center pt-2",
    type: "input",
  },
  "momentum.reset": {
    position: { y: 81, x: 4.4 },
    size: { height: 4.7, width: 8.7 },
    className: "absolute text-lg text-center pt-2",
    type: "input",
  },
};
