export const characterDataSchema = {
  player: {
    position: { y: 128, x: 548 },
    className: "absolute h-6 w-[152px] text-xl font-bold",
    placeholder: "",
    type: "input",
  },
  name: {
    position: { y: 190, x: 146 },
    className: "absolute h-5 w-[212px] text-lg font-bold",
    placeholder: "",
    type: "input",
  },
  age: {
    position: { y: 220, x: 123 },
    className: "absolute h-5 w-[230px] text-lg font-bold",
    placeholder: "",
    type: "input",
  },
  fear: {
    position: { y: 251, x: 127 },
    className: "absolute h-5 w-[228px] text-lg font-bold",
    placeholder: "",
    type: "input",
  },
  motivation: {
    position: { y: 282, x: 174 },
    className: "absolute h-5 w-[184px] text-lg font-bold",
    placeholder: "",
    type: "input",
  },
  motivation2: {
    position: { y: 310, x: 74 },
    className: "absolute h-5 w-[275px] text-lg font-bold",
    placeholder: "",
    type: "input",
  },
  flaws: {
    position: { y: 340, x: 168 },
    className: "absolute h-5 w-[182px] text-lg font-bold",
    placeholder: "",
    type: "input",
  },
  flaws2: {
    position: { y: 369, x: 74 },
    className: "absolute h-5 w-[275px] text-lg font-bold",
    placeholder: "",
    type: "input",
  },
  description: {
    position: { y: 400, x: 190 },
    className: "absolute h-5 w-[164px] text-lg font-bold",
    placeholder: "",
    type: "input",
  },
  description2: {
    position: { y: 429, x: 74 },
    className: "absolute h-5 w-[275px] text-lg font-bold",
    placeholder: "",
    type: "input",
  },
  description3: {
    position: { y: 457, x: 74 },
    className: "absolute h-5 w-[275px] text-lg font-bold",
    placeholder: "",
    type: "input",
  },
  description4: {
    position: { y: 485, x: 74 },
    className: "absolute h-5 w-[275px] text-lg font-bold",
    placeholder: "",
    type: "input",
  },
  fight: {
    position: { y: 228, x: 414 },
    className: "absolute h-12 w-[144px] font-bold text-center text-3xl",
    placeholder: "",
    type: "input",
  },
  flight: {
    position: { y: 228, x: 558 },
    className: "absolute h-12 w-[144px] font-bold text-center text-3xl",
    placeholder: "",
    type: "input",
  },
  brains: {
    position: { y: 316, x: 414 },
    className: "absolute h-12 w-[144px] font-bold text-center text-3xl",
    placeholder: "",
    type: "input",
  },
  brawn: {
    position: { y: 316, x: 558 },
    className: "absolute h-12 w-[144px] font-bold text-center text-3xl",
    placeholder: "",
    type: "input",
  },
  charm: {
    position: { y: 403, x: 414 },
    className: "absolute h-12 w-[144px] font-bold text-center text-3xl",
    placeholder: "",
    type: "input",
  },
  grit: {
    position: { y: 403, x: 558 },
    className: "absolute h-12 w-[144px] font-bold text-center text-3xl",
    placeholder: "",
    type: "input",
  },
  backpack: {
    position: { y: 553, x: 420 },
    className: "absolute h-36 w-[284px] font-bold text-lg",
    placeholder: "",
    type: "textarea",
  },
  tokens: {
    position: { y: 717, x: 646 },
    className: "absolute h-6 w-[65px] font-bold text-lg",
    placeholder: "",
    type: "input",
  },
  notes: {
    position: { y: 797, x: 348 },
    className: "absolute h-32 w-[365px] font-bold text-lg",
    placeholder: "",
    type: "textarea",
  },
  skilled: {
    position: { y: 752, x: 124 },
    className: "absolute h-6 w-[175px] font-bold text-lg",
    placeholder: "",
    type: "input",
  },
  wealthy: {
    type: "checkbox",
    position: { y: 554, x: 99 },
    className: "w-2 aspect-square",
  },
  lucky: {
    type: "checkbox",
    position: { y: 578, x: 99 },
    className: "w-2 aspect-square",
  },
  treasurehunter: {
    type: "checkbox",
    position: { y: 601, x: 99 },
    className: "w-2 aspect-square",
  },
  heal: {
    type: "checkbox",
    position: { y: 624, x: 99 },
    className: "w-2 aspect-square",
  },
  discreet: {
    type: "checkbox",
    position: { y: 648, x: 99 },
    className: "w-2 aspect-square",
  },
  tough: {
    type: "checkbox",
    position: { y: 671, x: 99 },
    className: "w-2 aspect-square",
  },
  cool: {
    type: "checkbox",
    position: { y: 694, x: 99 },
    className: "w-2 aspect-square",
  },
  rude: {
    type: "checkbox",
    position: { y: 718, x: 99 },
    className: "w-2 aspect-square",
  },
  skilledcheck: {
    type: "checkbox",
    position: { y: 740, x: 99 },
    className: "w-2 aspect-square",
  },
  heroic: {
    type: "checkbox",
    position: { y: 786, x: 99 },
    className: "w-2 aspect-square",
  },
  intuitive: {
    type: "checkbox",
    position: { y: 810, x: 99 },
    className: "w-2 aspect-square",
  },
  loyal: {
    type: "checkbox",
    position: { y: 834, x: 99 },
    className: "w-2 aspect-square",
  },
  prepared: {
    type: "checkbox",
    position: { y: 858, x: 99 },
    className: "w-2 aspect-square",
  },
  protector: {
    type: "checkbox",
    position: { y: 880, x: 99 },
    className: "w-2 aspect-square",
  },
  rebellious: {
    type: "checkbox",
    position: { y: 904, x: 99 },
    className: "w-2 aspect-square",
  },
  relaxed: {
    type: "checkbox",
    position: { y: 928, x: 99 },
    className: "w-2 aspect-square",
  },
};
