export const characterDataSchema = {
  player: {
    position: { y: 13, x: 71 },
    size: { width: 21, height: 2 },
    className: "absolute text-xl font-bold",
    placeholder: "",
    type: "input",
  },
  name: {
    position: { y: 18.4, x: 15.6 },
    size: { width: 29.2, height: 2 },
    className: "absolute text-lg font-bold",
    placeholder: "",
    type: "input",
  },
  age: {
    position: { y: 21.4, x: 12.6 },
    size: { width: 31.5, height: 2 },
    className: "absolute text-lg font-bold",
    placeholder: "",
    type: "input",
  },
  fear: {
    position: { y: 24.4, x: 13.2 },
    size: { width: 31, height: 2 },
    className: "absolute text-lg font-bold",
    placeholder: "",
    type: "input",
  },
  motivation: {
    position: { y: 27.3, x: 5.5 },
    size: { width: 39.4, height: 4.9 },
    className: "absolute font-bold leading-7",
    placeholder: "",
    type: "contenteditable",
    block: {
      className: "float-left",
      size: { width: 35, height: 45 },
    },
    textarea: {
      className: "font-shadows w-full h-full",
    },
  },
  flaws: {
    position: { y: 32.9, x: 5.5 },
    size: { width: 38.4, height: 5 },
    className: "absolute font-bold leading-7",
    placeholder: "",
    type: "contenteditable",
    block: {
      className: "float-left",
      size: { width: 34, height: 45 },
    },
    textarea: {
      className: "font-shadows w-full h-full",
    },
  },
  description: {
    position: { y: 38.3, x: 5.5 },
    size: { width: 39, height: 11 },
    className: "absolute font-bold leading-8",
    placeholder: "",
    type: "contenteditable",
    block: {
      className: "float-left",
      size: { width: 41, height: 23 },
    },
    textarea: {
      className: "font-shadows w-full h-full",
    },
  },
  fight: {
    position: { y: 22.2, x: 52.5 },
    size: { width: 20, height: 4.6 },
    className: "absolute text-lg font-bold text-center",
    placeholder: "",
    type: "input",
  },
  flight: {
    position: { y: 22.2, x: 72.2 },
    size: { width: 20, height: 4.6 },
    className: "absolute text-lg font-bold text-center",
    placeholder: "",
    type: "input",
  },
  brains: {
    position: { y: 30.8, x: 52.5 },
    size: { width: 20, height: 4.6 },
    className: "absolute text-lg font-bold text-center",
    placeholder: "",
    type: "input",
  },
  brawn: {
    position: { y: 30.8, x: 72.2 },
    size: { width: 20, height: 4.6 },
    className: "absolute text-lg font-bold text-center",
    placeholder: "",
    type: "input",
  },
  charm: {
    position: { y: 39.2, x: 52.5 },
    size: { width: 20, height: 4.6 },
    className: "absolute text-lg font-bold text-center",
    placeholder: "",
    type: "input",
  },
  grit: {
    position: { y: 39.2, x: 72.2 },
    size: { width: 20, height: 4.6 },
    className: "absolute text-lg font-bold text-center",
    placeholder: "",
    type: "input",
  },
  backpack: {
    position: { y: 52.6, x: 43 },
    size: { width: 52, height: 17 },
    className: "absolute font-bold leading-8",
    placeholder: "",
    type: "contenteditable",
    block: {
      className: "float-left",
      size: { width: 25, height: 49 },
    },
    textarea: {
      className: "font-shadows w-full h-full",
    },
  },
  tokens: {
    position: { y: 70.2, x: 84.5 },
    size: { width: 9, height: 2 },
    className: "absolute text-lg font-bold text-center",
    placeholder: "",
    type: "input",
  },
  notes: {
    position: { y: 74.8, x: 43 },
    size: { width: 52, height: 17.5 },
    className: "absolute font-bold leading-8",
    placeholder: "",
    type: "contenteditable",
    block: {
      className: "float-left",
      size: { width: 20, height: 15 },
    },
    textarea: {
      className: "font-shadows w-full h-full",
    },
  },
  skilled: {
    position: { y: 73.3, x: 12.8 },
    size: { width: 25, height: 2 },
    className: "absolute text-lg font-bold",
    placeholder: "",
    type: "input",
  },
  wealthy: {
    type: "checkbox",
    position: { y: 53.9, x: 8.9 },
    size: { width: 1.5 },
  },
  lucky: {
    type: "checkbox",
    position: { y: 56.1, x: 8.9 },
    size: { width: 1.5 },
  },
  treasurehunter: {
    type: "checkbox",
    position: { y: 58.5, x: 8.9 },
    size: { width: 1.5 },
  },
  heal: {
    type: "checkbox",
    position: { y: 60.8, x: 8.9 },
    size: { width: 1.5 },
  },
  discreet: {
    type: "checkbox",
    position: { y: 63, x: 8.9 },
    size: { width: 1.5 },
  },
  tough: {
    type: "checkbox",
    position: { y: 65.3, x: 8.9 },
    size: { width: 1.5 },
  },
  cool: {
    type: "checkbox",
    position: { y: 67.5, x: 8.9 },
    size: { width: 1.5 },
  },
  rude: {
    type: "checkbox",
    position: { y: 69.8, x: 8.9 },
    size: { width: 1.5 },
  },
  skilledcheck: {
    type: "checkbox",
    position: { y: 72.1, x: 8.9 },
    size: { width: 1.5 },
  },
  heroic: {
    type: "checkbox",
    position: { y: 76.5, x: 8.9 },
    size: { width: 1.5 },
  },
  intuitive: {
    type: "checkbox",
    position: { y: 78.9, x: 8.9 },
    size: { width: 1.5 },
  },
  loyal: {
    type: "checkbox",
    position: { y: 81.1, x: 8.9 },
    size: { width: 1.5 },
  },
  prepared: {
    type: "checkbox",
    position: { y: 83.4, x: 8.9 },
    size: { width: 1.5 },
  },
  protector: {
    type: "checkbox",
    position: { y: 85.6, x: 8.9 },
    size: { width: 1.5 },
  },
  rebellious: {
    type: "checkbox",
    position: { y: 87.9, x: 8.9 },
    size: { width: 1.5 },
  },
  relaxed: {
    type: "checkbox",
    position: { y: 90.3, x: 8.9 },
    size: { width: 1.5 },
  },
};
